services:
  - type: web
    name: medassist
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        value: medassist-render-secret-2026
      - key: DATABASE_URI
        value: sqlite:///medassist.db
      - key: FLASK_DEBUG
        value: 0